### ISSUE TITLE
request: log to notes

### ISSUE THREAD

**Issue by Trasoer** [dor-fvtt-released-modules/silence-compatibility-warnings#1]
not an issue but a suggestion: it is possible to log the warning you are suppressing to a note so it is still possible to check them later?
(also foundry needs to log those warnings in  a readable way, they flush out way to fast to be usefull)

**Comment by Doresain** [comment]
Technically possible, but would require a LOT more code and complexity - right now all I'm doing is toggling an internal setting for the user. This is, I think, out of scope for this little module.
